### ISSUE TITLE
Not really an issue more ... Talking? Idk how to contact you lol

### ISSUE THREAD

**Issue by SylverBean** [Butterstroke/MargarineBot#48]
I am not the only one who cannot find hydrabolt. 

```Looking at what I believe is the project you’re working on, when it tries to perform it’s npm install step it’s unable to find the discord.js repo you’re attempting to use. In the logs I see:

ERROR 404 Not Found: 
https://codeload.github.com/hydrabolt/discord.js/tar.gz/d92ee2ff999954899c891c093f5f107dd686b64f```

![image](https://user-images.githubusercontent.com/38189579/49347300-29526780-f66b-11e8-9e24-2ed596a40a8c.png)

This appears to actually be a common issue now that I look around more ...

**Comment by AurelicButter** [comment]
In terms of contacting, you can send an email to konirosen@protonmail.ch and for MargarineBot in particular, I do also provide the option to message me on Discord at Butterstroke#7150. This can be found in the TermsOfService.md file or just on my profile, for reference. (For messaging me, don't wait for me to be online, just drop it in my DMs. I'll respond to them when I look at Discord.)

That image in your message continues to solidify my theory I stated in #46 a couple weeks ago. I still stand by the statement I wrote a few weeks ago with it being a Glitch issue. 

> This appears to actually be a common issue

To ease my statistically-crazed mind, I must ask where you were looking around before I make any conclusions on this. Sources matter when it comes to statements like this. If it's all Glitch, that doesn't break my theory.

But in the end, I don't think I can help you much further with this. I have given my all to understand and solve the issue. If I was to revert to v11 (the version you could install successfully), not only would it be a rewrite of what I've done, I'd also need to develop a whole new framework to replace the old one that I would have to scrape because it would not work with the version. I don't have the time nor the resources to conduct such a overhaul.

If anything, Glitch support or the discord.js people will need to handle this issue and help you or whoever find a solution.

**Comment by SylverBean** [comment]
I looked around on glitch and heroku, as those are the most popular hosting sites that I know of. I dont want you to edit your bot at all lol, I was just saying its a semi-common(?) issue with that discord package :PPP Also, I sent a friend request on discord x3
