### ISSUE TITLE
Support Server

### ISSUE THREAD

**Issue by ffflick-gh** [Butterstroke/MargarineBot#50]
Add your support server in the README.md

**Comment by ffflick-gh** [comment]
Oh wait, last commit was last year? Darn.

**Comment by AurelicButter** [comment]
> Last commit was last year

Not quite. Last commit for the master branch. There's another branch that I've updated a couple months ago. It's just that life gets in the way of things and that's what's kind of slowed down my progress here. I still offer support and answers in the meantime.

> Support server

There technically isn't one at the moment. I have debated making one in the past but never did since many people contact me through other means (Like Discord or Github Issues) and that often works out for me since I don't have a bazillion folks contacting me about things.

**Comment by ffflick-gh** [comment]
I didn't see your discord tag so I opened an issue for a support server.

**Comment by AurelicButter** [comment]
It's completely fine. Whatever works, works. I'm fine with either. 

I'll leave this issue open in the meantime for future me to think about a support server/making the contact information a bit easier to find.

**Comment by AurelicButter** [comment]
I've added a support server link and contact section in the README file. So, we should be all good to go with this now.
