### ISSUE TITLE
How to set bot activity

### ISSUE THREAD

**Issue by ghost** [Butterstroke/MargarineBot#69]
so i have digged every where and am unable to find out HOW TO SET THE BOT ACTIVITY, or if there is a code already WHERE IS IT

Aaaaaaaaaaaaaa

**Comment by AurelicButter** [comment]
You have to be a bot owner (either primary or secondary owner will work) in order to change the bot activity. 

If you have those permission levels, you should be able to see a command called "presence" in the Owner category when going through the help menu. Use the help command to figure out how to use the command. By default, it should be `m~help presence`.

**Comment by AurelicButter** [comment]
Hearing no further questions, I'll be closing this issue now.
